# Generated by Django 4.1.2 on 2022-11-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaApp', '0002_especialidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_consultorio', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClinicaApp.persona')),
                ('id_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ClinicaApp.obrassociales', verbose_name='Obra Social')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
            bases=('ClinicaApp.persona',),
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ClinicaApp.persona')),
                ('id_consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClinicaApp.consultorios', verbose_name='Consultorio')),
                ('id_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ClinicaApp.especialidades', verbose_name='Especialidad')),
            ],
            bases=('ClinicaApp.persona',),
        ),
    ]
